#!/bin/sh

yell() { printf '%s: %s' "$0" "$*" >&2; printf '\nAn error occured. \xE2\x9D\x8C \n';}
die() { yell "$1"; exit 111; }
try() { "$@" || die "cannot $*"; }

NL=$(printf '\n');
script='"scripts": {';
npmStart="$NL   \"start\": \"nodemon --exec babel-node src/index.js\",";
babelrc='{\n"presets": [\n    "@babel/preset-env"\n  ]\n}\n';

if [ $# -lt 1 ]; then
  echo 'enter the project name';
else
  try mkdir -p "$1" && false;     # mkdir returns 1 if it fails
  try cd "$1" && npm init -y;
  try mkdir src && touch src/index.js .env;
  try printf "$babelrc" > .babelrc;
  try sed -i "" "s|$script|$script$npmStart|g" ./package.json;
  try npm install nodemon @babel/core @babel/node @babel/preset-env --save-dev;
  try npm install dotenv --save;
  printf 'Project %s is setup with nodemon babel & dotenv \xE2\x9C\x85\n' "$1";
fi
